Repository CalmCrews/silver_backend, pull requests merged in 2023-07, with the labels that each got.

#5 setting: jazzmin-admin
  webapp/config/settings/base.py
  webapp/requirements.txt
Labels: settings

#7 Hotfix: debug 모드 상관 없이 swagger url 연결
  webapp/config/urls.py
Labels: fix, release

#13 chore: cors 및 csrf 설정
  webapp/config/authentications.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/requirements.txt
Labels: settings

#14 feature: user model 구현
  webapp/__init__.py
  webapp/config/models.py
  webapp/config/settings/base.py
  webapp/requirements.txt
  webapp/user/__init__.py
  webapp/user/admin/__init__.py
  webapp/user/admin/userAdmin.py
  webapp/user/apps.py
  webapp/user/migrations/0001_initial.py
  webapp/user/migrations/__init__.py
  webapp/user/models/__init__.py
  webapp/user/models/user.py
  webapp/user/tests.py
  webapp/user/views.py
Labels: feature

#15 feature: jwt authentication
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/requirements.txt
  webapp/user/serializers/__init__.py
  webapp/user/serializers/loginSerializer.py
  webapp/user/serializers/logoutSerializer.py
  webapp/user/serializers/userSerializer.py
  webapp/user/urls.py
  webapp/user/views.py
  webapp/user/views/__init__.py
  webapp/user/views/jwtLoginAPIView.py
  webapp/user/views/logoutAPIView.py
  webapp/user/views/registerAPIView.py
Labels: feature

#16 feature: kakao login
  webapp/config/settings/base.py
  webapp/config/settings/development.py
  webapp/config/settings/production.py
  webapp/requirements.txt
  webapp/user/migrations/0002_user_kakaoid_alter_user_username.py
  webapp/user/models/user.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/kakaoUserView.py
Labels: feature

#17 fix: response 데이터 변경
  webapp/user/models/user.py
  webapp/user/views/kakaoUserView.py
Labels: fix

#20 fix: kakao login response 수정
  webapp/user/views/kakaoUserView.py
Labels: fix

#23 Feature: product model
  webapp/config/settings/base.py
  webapp/product/__init__.py
  webapp/product/admin.py
  webapp/product/admin/__init__.py
  webapp/product/admin/productAdmin.py
  webapp/product/apps.py
  webapp/product/migrations/0001_initial.py
  webapp/product/migrations/__init__.py
  webapp/product/models/__init__.py
  webapp/product/models/product.py
  webapp/product/tests.py
  webapp/product/views.py
  webapp/user/admin/userAdmin.py
  webapp/user/models/user.py
Labels: feature

#25 Feature: product view 구현
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/product/admin.py
  webapp/product/migrations/0002_product_thumbnail_product_video.py
  webapp/product/models/product.py
  webapp/product/serializers/__init__.py
  webapp/product/serializers/productListSerializer.py
  webapp/product/serializers/productSerializer.py
  webapp/product/urls.py
  webapp/product/views.py
  webapp/product/views/__init__.py
  webapp/product/views/productListAPIView.py
  webapp/product/views/productRetrieveAPIView.py
Labels: feature

#27 Feature/club model
  webapp/club/__init__.py
  webapp/club/admin/__init__.py
  webapp/club/admin/clubAdmin.py
  webapp/club/admin/clubtagAdmin.py
  webapp/club/apps.py
  webapp/club/migrations/0001_initial.py
  webapp/club/migrations/0002_clubtag.py
  webapp/club/migrations/0003_alter_clubtag_club.py
  webapp/club/migrations/__init__.py
  webapp/club/models/__init__.py
  webapp/club/models/club.py
  webapp/club/models/clubTag.py
  webapp/club/tests.py
  webapp/club/urls.py
  webapp/club/views.py
  webapp/config/settings/base.py
Labels: feature

#29 Feature: 상품 Q&A 모델 및 기능 구현
  webapp/product/admin/__init__.py
  webapp/product/admin/answerAdmin.py
  webapp/product/admin/productQnAAdmin.py
  webapp/product/admin/questionAdmin.py
  webapp/product/migrations/0003_productanswer_productquestion_productqna.py
  webapp/product/migrations/0004_alter_productqna_answer.py
  webapp/product/models/__init__.py
  webapp/product/models/product.py
  webapp/product/models/productAnswer.py
  webapp/product/models/productQnA.py
  webapp/product/models/productQuestion.py
  webapp/product/permissions.py
  webapp/product/serializers/__init__.py
  webapp/product/serializers/productAnswerSerializer.py
  webapp/product/serializers/productListSerializer.py
  webapp/product/serializers/productQnASerializer.py
  webapp/product/serializers/productQuestionSerializer.py
  webapp/product/serializers/productSerializer.py
  webapp/product/urls.py
  webapp/product/views/__init__.py
  webapp/product/views/productListAPIView.py
  webapp/product/views/productQnAListAPIView.py
  webapp/product/views/productQnARetriveAPIView.py
  webapp/product/views/productQuestionCreateAPIView.py
  webapp/product/views/productQuestionRetrieveUpdateDestroyAPIView.py
Labels: feature

#32 Feature: 상품 태그 모델 생성
  webapp/product/migrations/0005_producttag.py
  webapp/product/migrations/0006_alter_producttag_product.py
  webapp/product/models/__init__.py
  webapp/product/models/productTag.py
Labels: feature

#33 Feature: Order app 및 model
  webapp/config/settings/base.py
  webapp/order/__init__.py
  webapp/order/admin/__init__.py
  webapp/order/admin/orderAdmin.py
  webapp/order/apps.py
  webapp/order/migrations/0001_initial.py
  webapp/order/migrations/__init__.py
  webapp/order/models/__init__.py
  webapp/order/models/order.py
  webapp/order/tests.py
  webapp/order/views.py
  webapp/user/migrations/0005_user_balance.py
  webapp/user/models/user.py
Labels: feature

#37 Feature: order api
  webapp/order/migrations/0002_alter_order_final_price_alter_order_initial_price.py
  webapp/order/models/order.py
  webapp/order/serializers/__init__.py
  webapp/order/serializers/orderSerializer.py
  webapp/order/urls.py
  webapp/order/views.py
  webapp/order/views/__init__.py
  webapp/order/views/myOrderListForAllProductsAPIView.py
  webapp/order/views/orderListCreateAPIView.py
  webapp/order/views/orderRetrieveUpdateDestroyAPIView.py
  webapp/product/migrations/0007_alter_product_total.py
  webapp/product/models/product.py
  webapp/product/serializers/__init__.py
  webapp/product/serializers/productAbstractSerializer.py
  webapp/product/serializers/productSerializer.py
  webapp/product/urls.py
  webapp/product/views/productQnAListAPIView.py
  webapp/product/views/productQuestionCreateAPIView.py
  webapp/product/views/productQuestionRetrieveUpdateDestroyAPIView.py
  webapp/user/urls.py
Labels: feature

#40 Feature: crontab을 이용한 order logic 구현
  docker-compose.production.yml
  docker-compose.yml
  webapp/Dockerfile
  webapp/Dockerfile.production
  webapp/config/settings/base.py
  webapp/docker-entrypoint.production.sh
  webapp/order/scheduler.py
  webapp/order/views/orderListCreateAPIView.py
  webapp/requirements.txt
  webapp/user/migrations/0006_alter_user_balance.py
  webapp/user/models/user.py
Labels: feature
