Repository CalmCrews/silver_backend, pull requests merged in 2023-08, with the labels that each got.

#43 Feature/club CRUD 간단하게 구현
  webapp/club/admin/__init__.py
  webapp/club/admin/userclubAdmin.py
  webapp/club/migrations/0004_userclub.py
  webapp/club/migrations/0005_alter_userclub_nickname.py
  webapp/club/migrations/0006_alter_userclub_nickname.py
  webapp/club/models/__init__.py
  webapp/club/models/club.py
  webapp/club/models/clubTag.py
  webapp/club/models/userClub.py
  webapp/club/serializers/__init__.py
  webapp/club/serializers/clubListSerializer.py
  webapp/club/serializers/clubRetrieveSerializer.py
  webapp/club/serializers/clubSerializer.py
  webapp/club/serializers/clubTagSerializer.py
  webapp/club/serializers/userClubNicknameSerializer.py
  webapp/club/serializers/userClubSerializer.py
  webapp/club/urls.py
  webapp/club/views.py
  webapp/club/views/__init__.py
  webapp/club/views/clubListCreateAPIView.py
  webapp/club/views/clubRetrieveUpdateAPIView.py
  webapp/club/views/userClubNicknameUpdateAPIView.py
  webapp/config/urls.py
Labels: feature

#54 Feature: 상품 카테고리별 필터링
  webapp/config/settings/base.py
  webapp/product/views/productListAPIView.py
  webapp/requirements.txt
Labels: feature

#59 Feature: 소셜 로그인에서 닉네임 정보를 받아와서 저장
  webapp/user/views/kakaoUserView.py
  webapp/user/views/naverUserView.py
Labels: feature

#61 Feature: 유저 잔액 충전 및 조회
  webapp/user/admin/userAdmin.py
  webapp/user/models/user.py
  webapp/user/permissions/__init__.py
  webapp/user/permissions/isUserCurrentUser.py
  webapp/user/serializers/__init__.py
  webapp/user/serializers/userBalanceSerializer.py
  webapp/user/serializers/userSerializer.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/chargeBalanceAPIView.py
Labels: feature

#60 Feature/userclubjoincreateAPIView 기능 생성(클럽 코드 입력시에 userclub에 추가)
  webapp/club/serializers/__init__.py
  webapp/club/serializers/userClubJoinSerializer.py
  webapp/club/urls.py
  webapp/club/views/__init__.py
  webapp/club/views/userClubJoinCreateAPIVIew.py
Labels: feature

#62 Feature: club product model
  webapp/club/admin/__init__.py
  webapp/club/admin/clubProductAdmin.py
  webapp/club/migrations/0007_clubproduct.py
  webapp/club/models/__init__.py
  webapp/club/models/clubProduct.py
Labels: feature

#64 refactor: order model 수정, url 주석 처리
  webapp/order/migrations/0003_alter_order_product.py
  webapp/order/models/order.py
  webapp/order/urls.py
Labels: refactor

#72 Feature/nickname
  webapp/user/migrations/0008_alter_user_nickname.py
  webapp/user/models/user.py
  webapp/user/serializers/userNicknameSerializer.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/duplicateNicknameAPIView.py
  webapp/user/views/nicknameUpdateAPIVIew.py
Labels: feature

#73 Feature: 리뷰 api 및 코드 리팩토링
  webapp/club/admin/clubAdmin.py
  webapp/club/admin/clubProductAdmin.py
  webapp/club/admin/clubtagAdmin.py
  webapp/club/admin/userclubAdmin.py
  webapp/club/migrations/0008_remove_clubproduct_maximum.py
  webapp/club/models/club.py
  webapp/club/models/clubProduct.py
  webapp/club/serializers/__init__.py
  webapp/club/serializers/clubListSerializer.py
  webapp/club/serializers/clubProductSerializer.py
  webapp/club/serializers/clubRetrieveSerializer.py
  webapp/club/serializers/userClubJoinSerializer.py
  webapp/club/urls.py
  webapp/club/views/__init__.py
  webapp/club/views/clubListCreateAPIView.py
  webapp/club/views/clubRetrieveUpdateAPIView.py
  webapp/club/views/duplicateNicknameAPIView.py
  webapp/order/migrations/0005_alter_order_quantity.py
  webapp/order/models/order.py
  webapp/order/permissions.py
  webapp/order/scheduler.py
  webapp/order/serializers/orderSerializer.py
  webapp/order/urls.py
  webapp/order/views/__init__.py
  webapp/order/views/myOrderListForAllProductsAPIView.py
  webapp/order/views/orderListCreateAPIView.py
  webapp/order/views/orderRetrieveUpdateDestroyAPIView.py
  webapp/product/admin/productAdmin.py
  webapp/product/migrations/0008_remove_product_total.py
  webapp/product/models/product.py
  webapp/product/serializers/productSerializer.py
  webapp/product/urls.py
  webapp/product/views/__init__.py
  webapp/product/views/clubProductCreateAPIView.py
  webapp/review/migrations/0003_alter_review_rating.py
  webapp/review/models/review.py
  webapp/review/serializers/__init__.py
  webapp/review/serializers/reviewSerializer.py
  webapp/review/urls.py
  webapp/review/views.py
  webapp/review/views/__init__.py
  webapp/review/views/reviewListCreateAPIView.py
  webapp/user/urls.py
Labels: feature

#75 Feature/판매자 모델 생성 및 admin 연결
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/seller/__init__.py
  webapp/seller/admin.py
  webapp/seller/admin/__init__.py
  webapp/seller/admin/sellerAdmin.py
  webapp/seller/apps.py
  webapp/seller/migrations/0001_initial.py
  webapp/seller/migrations/__init__.py
  webapp/seller/models.py
  webapp/seller/models/__init__.py
  webapp/seller/models/seller.py
  webapp/seller/serializers/__init__.py
  webapp/seller/tests.py
  webapp/seller/urls.py
  webapp/seller/views/__init__.py
Labels: feature

#77 feat: 판매자 상세 페이지 sellerRetrieveAPIView 구현
  webapp/club/views/duplicateNicknameAPIView.py
  webapp/config/urls.py
  webapp/product/migrations/0009_alter_product_seller.py
  webapp/product/models/product.py
  webapp/product/serializers/productListSerializer.py
  webapp/product/serializers/productSerializer.py
  webapp/seller/admin/sellerAdmin.py
  webapp/seller/migrations/0002_alter_seller_represent.py
  webapp/seller/migrations/0003_seller_business_image.py
  webapp/seller/models.py
  webapp/seller/models/seller.py
  webapp/seller/serializers/sellerSerializer.py
  webapp/seller/urls.py
  webapp/seller/views/__init__.py
  webapp/seller/views/sellerRetrieveAPIView.py
Labels: feature

#78 [Refactor] clubTag model 삭제 및 club에 필드 추가 api, serializer 리팩토링
  webapp/club/admin/__init__.py
  webapp/club/admin/clubAdmin.py
  webapp/club/admin/clubtagAdmin.py
  webapp/club/migrations/0009_club_tag_alter_club_name_delete_clubtag.py
  webapp/club/migrations/0010_alter_club_tag.py
  webapp/club/models/__init__.py
  webapp/club/models/club.py
  webapp/club/models/clubTag.py
  webapp/club/serializers/__init__.py
  webapp/club/serializers/clubListSerializer.py
  webapp/club/serializers/clubRetrieveSerializer.py
  webapp/club/serializers/clubSerializer.py
  webapp/club/serializers/clubTagSerializer.py
  webapp/club/serializers/userClubSerializer.py
  webapp/club/views/clubListCreateAPIView.py
Labels: refactor

#80 Feature: 모임에서 공동구매 달성률 표시
  webapp/club/models/clubProduct.py
  webapp/club/serializers/clubProductAbstractSerializer.py
  webapp/club/serializers/clubProductSerializer.py
Labels: feature

#82 [Feature] club 레벨 업 구현
  webapp/club/migrations/0011_club_achievement.py
  webapp/club/migrations/0012_clubproduct_registration.py
  webapp/club/migrations/0013_remove_club_achievement_club_achievement_count.py
  webapp/club/models/club.py
  webapp/club/models/clubProduct.py
  webapp/club/scheduler.py
  webapp/config/settings/base.py
  webapp/user/serializers/__init__.py
  webapp/user/views/nicknameUpdateAPIVIew.py
Labels: feature

#84 feat: 상품 추천 API
  webapp/club/views/userClubJoinCreateAPIVIew.py
  webapp/product/migrations/0010_product_tag_delete_producttag.py
  webapp/product/models/__init__.py
  webapp/product/models/product.py
  webapp/product/models/productTag.py
  webapp/product/urls.py
  webapp/product/views/proudctRecommandListAPIView.py
Labels: feature

#86 Feature/service qn a
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/service/__init__.py
  webapp/service/admin/__init__.py
  webapp/service/admin/answerAdmin.py
  webapp/service/admin/questionAdmin.py
  webapp/service/admin/serviceQnAAdmin.py
  webapp/service/apps.py
  webapp/service/migrations/0001_initial.py
  webapp/service/migrations/__init__.py
  webapp/service/models/__init__.py
  webapp/service/models/serviceAnswer.py
  webapp/service/models/serviceQnA.py
  webapp/service/models/serviceQuestion.py
  webapp/service/serializers/__init__.py
  webapp/service/serializers/serviceAnswerSerializer.py
  webapp/service/serializers/serviceQnASerializer.py
  webapp/service/serializers/serviceQuestionSerializer.py
  webapp/service/tests.py
  webapp/service/urls.py
  webapp/service/views/__init__.py
  webapp/service/views/serviceQnAListAPIView.py
  webapp/service/views/serviceQnARetriveAPIView.py
  webapp/service/views/serviceQuestionCreateAPIView.py
  webapp/service/views/serviceQuestionRetrieveUpdateDestroyAPIView.py
Labels: feature

#88 feat: notification 기능 구현
  webapp/club/serializers/clubRetrieveSerializer.py
  webapp/club/views/clubRetrieveUpdateAPIView.py
  webapp/club/views/userClubJoinCreateAPIVIew.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/notification/__init__.py
  webapp/notification/admin/__init__.py
  webapp/notification/admin/notificationAdmin.py
  webapp/notification/admin/usernotificationAdmin.py
  webapp/notification/apps.py
  webapp/notification/migrations/0001_initial.py
  webapp/notification/migrations/0002_notification_product.py
  webapp/notification/migrations/0003_alter_notification_category_and_more.py
  webapp/notification/migrations/0004_notification_club.py
  webapp/notification/migrations/0005_remove_notification_club_remove_notification_product_and_more.py
  webapp/notification/migrations/0006_alter_usernotification_notification_and_more.py
  webapp/notification/migrations/__init__.py
  webapp/notification/models/__init__.py
  webapp/notification/models/notification.py
  webapp/notification/models/userNotification.py
  webapp/notification/serializers/__init__.py
  webapp/notification/serializers/notificationSerializer.py
  webapp/notification/serializers/usernotificationRetrieveSerializer.py
  webapp/notification/tests.py
  webapp/notification/urls.py
  webapp/notification/views/__init__.py
  webapp/notification/views/notificationListAPIView.py
  webapp/notification/views/userNotificationRetrieveAPIView.py
  webapp/product/views/clubProductCreateAPIView.py
Labels: feature

#90 feat: intial data 설정
  docker-compose.yml
  webapp/business_image/product1.jpg
  webapp/business_image/product10.jpg
  webapp/business_image/product11.jpg
  webapp/business_image/product12.jpg
  webapp/business_image/product13.jpg
  webapp/business_image/product14.jpg
  webapp/business_image/product15.jpg
  webapp/business_image/product2.jpg
  webapp/business_image/product3.jpg
  webapp/business_image/product4.jpg
  webapp/business_image/product5.jpg
  webapp/business_image/product6.jpg
  webapp/business_image/product7.jpg
  webapp/business_image/product8.jpg
  webapp/business_image/product9.jpg
  webapp/business_image/seller1.jpg
  webapp/business_image/seller2.jpg
  webapp/business_image/seller3.jpg
  webapp/business_image/seller4.jpg
  webapp/business_image/seller5.jpg
  webapp/business_image/seller6.jpg
  webapp/business_image/seller7.jpg
  webapp/docker-entrypoint.production.sh
  webapp/docker-entrypoint.sh
  webapp/product.json
  webapp/product/migrations/0013_alter_product_thumbnail.py
  webapp/product/migrations/0014_alter_product_thumbnail.py
  webapp/seller.json
  webapp/seller/migrations/0006_alter_seller_business_image.py
  webapp/seller/models/seller.py
Labels: feature

#92 [Refactor] clubProduct 예외 처리, club Level 다시 머지
  webapp/club/views/clubProductListAPIView.py
  webapp/club/views/clubProductRetrieveAPIView.py
  webapp/club/views/userClubJoinCreateAPIVIew.py
Labels: refactor

#98 Fix/orderproduct
  webapp/club/views/clubProductRetrieveAPIView.py
  webapp/order/views/orderListCreateAPIView.py
Labels: fix
